### ISSUE TITLE
Unable to start SinkRunner

### ISSUE THREAD

**Issue by akstatic** [btoddb/flume-ng-cassandra-sink#10]
I am getting following exception when I am starting flume with command bin/flume-ng agent --conf conf --conf-file conf/flume.conf --name agent.

27 Dec 2013 17:47:51,360 ERROR [lifecycleSupervisor-1-2](org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run:253)  - Unable to start SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@f684bc0 counterGroup:{ name:null counters:{} } } - Exception follows.
com.ecyrd.speed4j.ConfigurationException: No logger by the name hector-Logging found.
        at com.ecyrd.speed4j.StopWatchFactory.getInstance(StopWatchFactory.java:264)
        at me.prettyprint.cassandra.connection.SpeedForJOpTimer.<init>(SpeedForJOpTimer.java:15)
        at com.btoddb.flume.sinks.cassandra.CassandraSinkRepository.init(CassandraSinkRepository.java:99)
        at com.btoddb.flume.sinks.cassandra.CassandraSink.start(CassandraSink.java:95)
        at org.apache.flume.sink.DefaultSinkProcessor.start(DefaultSinkProcessor.java:46)
        at org.apache.flume.SinkRunner.start(SinkRunner.java:79)
        at org.apache.flume.lifecycle.LifecycleSupervisor$MonitorRunnable.run(LifecycleSupervisor.java:251)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)

I tried googling to get some results but couldn't find related information. Here is the config file I have used. Any help is appreciated. 

agent.sources = src-1
agent.channels = channel1
agent.sinks = cassandraSink

agent.sources.src-1.type = spooldir
agent.sources.src-1.channels = channel1
agent.sources.src-1.spoolDir = /var/log/test/dir
agent.sources.src-1.fileHeader = true

agent.sources.src-1.interceptors = addHost addTimestamp
agent.sources.src-1.interceptors.addHost.type = org.apache.flume.interceptor.HostInterceptor$Builder
agent.sources.src-1.interceptors.addHost.preserveExisting = false
agent.sources.src-1.interceptors.addHost.useIP = false
agent.sources.src-1.interceptors.addHost.hostHeader = host

agent.sources.src-1.interceptors.addTimestamp.type = org.apache.flume.interceptor.TimestampInterceptor$Builder

agent.channels.channel1.type = memory
agent.channels.channel1.capacity = 1000
### agent.channels.channel1.dataDirs = file-channel1/data

agent.sinks.cassandraSink.channel = channel1

agent.sinks.cassandraSink.type = com.btoddb.flume.sinks.cassandra.CassandraSink
agent.sinks.cassandraSink.hosts = localhost

**Comment by akstatic** [comment]
I had added one logger to the speed4j.properties file, I was able to solve this issue by removing that partilar logger entry. Thanks.
