### ISSUE TITLE
Transaction Issue

### ISSUE THREAD

**Issue by roycamp** [btoddb/flume-ng-cassandra-sink#2]
I'm testing the event reliability and I'm using  a file channel and killing Cassandra but it appears despite throwing an error, the transaction is still committed instead of rolled back. 

The following is the expected error I'm trying to create:
CassandraWriteWork.java:30)] exception while executing mutator
me.prettyprint.hector.api.exceptions.HectorException: All host pools marked down. Retry burden pushed out to client.
        at me.prettyprint.cassandra.connection.HConnectionManager.getClientFromLBPolicy(HConnectionManager.java:393)
        at me.prettyprint.cassandra.connection.HConnectionManager.operateWithFailover(HConnectionManager.java:249)
        at me.prettyprint.cassandra.model.ExecutingKeyspace.doExecuteOperation(ExecutingKeyspace.java:97)
        at me.prettyprint.cassandra.model.MutatorImpl.execute(MutatorImpl.java:243)
        at com.btoddb.flume.sinks.cassandra.CassandraWriteWork.run(CassandraWriteWork.java:27)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)

After this error is thrown then CassandraSink.java line ~177:
transaction.commit();
is called. Somewhere the exception is getting lost.  About to look into it more.

**Comment by btoddb** [comment]
good catch ... did u find a fix?

the problem i see is that the mutation is executed in a thread (CassandraWriteWork.)  the exception is caught there, but not exposed to the executing client in CassandraJob.waitUntilFinished()

i'll try to fix tonight or soon unless u want to tackle it

**Comment by roycamp** [comment]
I did a temporary fix but I doubt its ideal.  I basically stored the exception in a variable if it was raised and then checked for it later.

**Comment by btoddb** [comment]
ok, i just commited a fix, but i have not tested it.  unit tests pass ... i know this isn't awesome, but can you give it a try
