### ISSUE TITLE
Sink is falling over when dealing with large event data

### ISSUE THREAD

**Issue by viktort** [btoddb/flume-ng-cassandra-sink#8]
With the follwing error

``` sh
ERROR [SinkRunner-PollingRunner-DefaultSinkProcessor] (com.btoddb.flume.sinks.cassandra.CassandraSink.process:184)  - exception while processing in Cassandra Sink
java.lang.NumberFormatException: null
    at java.lang.Long.parseLong(Long.java:401)
    at java.lang.Long.parseLong(Long.java:478)
    at com.btoddb.flume.sinks.cassandra.FlumeLogEvent.getTimestamp(FlumeLogEvent.java:67)
    at com.btoddb.flume.sinks.cassandra.CassandraSinkRepository.saveToCassandra(CassandraSinkRepository.java:117)
    at com.btoddb.flume.sinks.cassandra.CassandraSink.process(CassandraSink.java:157)
    at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
    at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
    at java.lang.Thread.run(Thread.java:636)
13 Nov 2013 12:22:38,380 ERROR [SinkRunner-PollingRunner-DefaultSinkProcessor] (org.apache.flume.SinkRunner$PollingRunner.run:160)  - Unable to deliver event. Exception follows.
org.apache.flume.EventDeliveryException: Failed to persist message
    at com.btoddb.flume.sinks.cassandra.CassandraSink.process(CassandraSink.java:185)
    at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
    at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
    at java.lang.Thread.run(Thread.java:636)
Caused by: java.lang.NumberFormatException: null
    at java.lang.Long.parseLong(Long.java:401)
    at java.lang.Long.parseLong(Long.java:478)
    at com.btoddb.flume.sinks.cassandra.FlumeLogEvent.getTimestamp(FlumeLogEvent.java:67)
    at com.btoddb.flume.sinks.cassandra.CassandraSinkRepository.saveToCassandra(CassandraSinkRepository.java:117)
    at com.btoddb.flume.sinks.cassandra.CassandraSink.process(CassandraSink.java:157)
    ... 3 more
```

It can handle a number of these requests in one go but when I'm load testing with a multitude of these requests then I get the above error.

I have 5 minute log files which I drop into the flume spooling directory as Im using the Spooling Dir Source. So far I have sinked successfully a 153Mb file which contains smaller request payloads.

Even a 40Mb file with the larger requests is causing the above error.

My flume config is as follows

``` sh
orion.sources = spoolDir
orion.channels = fileChannel
orion.sinks= cassandra

orion.channels.fileChannel.type = file
#orion.channels.fileChannel.capacity = 100000
#orion.channels.fileChannel.transactionCapacity = 10000
orion.channels.fileChannel.keep-alive = 60
orion.channels.fileChannel.write-timeout = 60

# Describe the sink
orion.sinks.cassandra.type = com.btoddb.flume.sinks.cassandra.CassandraSink
orion.sinks.cassandra.hosts = <ip>
orion.sinks.cassandra.cluster_name = <cluster_name>
orion.sinks.cassandra.port = 9160
orion.sinks.cassandra.keyspace-name = Foo
orion.sinks.cassandra.records-colfam = bar

orion.sources.spoolDir.type = spooldir
orion.sources.spoolDir.spoolDir = /mnt/log/orion/flumeSpooling
#orion.sources.spoolDir.deserializer = LINE
orion.sources.spoolDir.inputCharset = UTF-8
orion.sources.spoolDir.deserializer.maxLineLength = 209715200
orion.sources.spoolDir.deletePolicy = never
orion.sources.spoolDir.interceptors = addSrc addHost addTimestamp addUUID

orion.sources.spoolDir.interceptors.addSrc.type = regex_extractor
orion.sources.spoolDir.interceptors.addSrc.regex = \"service\"\:\"([^"]*)
orion.sources.spoolDir.interceptors.addSrc.serializers = s1
orion.sources.spoolDir.interceptors.addSrc.serializers.s1.name = src

orion.sources.spoolDir.interceptors.addUUID.type = regex_extractor
orion.sources.spoolDir.interceptors.addUUID.regex = \"uuid\"\:\"([^"]*)
orion.sources.spoolDir.interceptors.addUUID.serializers = s1
orion.sources.spoolDir.interceptors.addUUID.serializers.s1.name = key

orion.sources.spoolDir.interceptors.addHost.type = org.apache.flume.interceptor.HostInterceptor$Builder
orion.sources.spoolDir.interceptors.addHost.preserveExisting = false
orion.sources.spoolDir.interceptors.addHost.useIP = true
orion.sources.spoolDir.interceptors.addHost.hostHeader = host

orion.sources.spoolDir.interceptors.addTimestamp.type = regex_extractor
orion.sources.spoolDir.interceptors.addTimestamp.regex = \"timestamp\"\:\"([^"]*)
orion.sources.spoolDir.interceptors.addTimestamp.serializers = s1
orion.sources.spoolDir.interceptors.addTimestamp.serializers.s1.name = timestamp

orion.sources.spoolDir.channels = fileChannel
orion.sinks.cassandra.channel = fileChannel
```

Without looking at the code it appears that when an event is read from the channel its ending up truncated missing out the timestamp causing the above error.

Looking through the code now but any help would be appreciated.

All the best,

viktort

**Comment by viktort** [comment]
Hi @btoddb,

Nothing wrong with the sink here but the channel. Changed to a file sink and saw that data was indeed truncated  which is ending up the same when doing event = channel.take(); the data is corrupt.

Changing to use the memory channel instead.

Thanks,

Viktor
