### ISSUE TITLE
Sink-NumberFormatException

### ISSUE THREAD

**Issue by salihkardan** [btoddb/flume-ng-cassandra-sink#9]
Hi,

I am using flume-1.4.0 and cassandra-2.0.0. While sink trying to insert data into cassandra, I get this error: 
# error

java.lang.NumberFormatException: null
    at java.lang.Long.parseLong(Long.java:404)
    at java.lang.Long.parseLong(Long.java:483)
    at com.btoddb.flume.sinks.cassandra.FlumeLogEvent.getTimestamp(FlumeLogEvent.java:67)
    at com.btoddb.flume.sinks.cassandra.CassandraSinkRepository.saveToCassandra(CassandraSinkRepository.java:117)
    at com.btoddb.flume.sinks.cassandra.CassandraSink.process(CassandraSink.java:157)
    at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
    at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
    at java.lang.Thread.run(Thread.java:724)
13/12/05 08:07:21 ERROR flume.SinkRunner: Unable to deliver event. Exception follows.
org.apache.flume.EventDeliveryException: Failed to persist message
    at com.btoddb.flume.sinks.cassandra.CassandraSink.process(CassandraSink.java:185)
    at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:68)
    at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:147)
    at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.NumberFormatException: null
    at java.lang.Long.parseLong(Long.java:404)
    at java.lang.Long.parseLong(Long.java:483)
    at com.btoddb.flume.sinks.cassandra.FlumeLogEvent.getTimestamp(FlumeLogEvent.java:67)
    at com.btoddb.flume.sinks.cassandra.CassandraSinkRepository.saveToCassandra(CassandraSinkRepository.java:117)
    at com.btoddb.flume.sinks.cassandra.CassandraSink.process(CassandraSink.java:157)
    ... 3 more
# conf file

By the way I am adding timestamp with org.apache.flume.interceptor.TimestampInterceptor. Here is my conf file. 
(It is just a test so forget about the key value in the header)

agent.sources = avrosource
agent.channels = channel1
agent.sinks = cassandraSink

agent.sources.avrosource.type = avro
agent.sources.avrosource.channels = channel1
agent.sources.avrosource.bind = localhost
agent.sources.avrosource.port = 4141

agent.sources.avrosource.interceptors = addHost addTimestamp
agent.sources.avrosource.interceptors.addHost.type = org.apache.flume.interceptor.HostInterceptor$Builder
agent.sources.avrosource.interceptors.addHost.preserveExisting = false
agent.sources.avrosource.interceptors.addHost.useIP = false
agent.sources.avrosource.interceptors.addHost.hostHeader = host

agent.sources.avrosource.interceptors.addTimestamp.type = org.apache.flume.interceptor.TimestampInterceptor$Builder

agent.sources.avrosource.interceptors = a
agent.sources.avrosource.interceptors.a.type = static
agent.sources.avrosource.interceptors.a.key = key
agent.sources.avrosource.interceptors.a.value = value

agent.channels.channel1.type = memory
agent.channels.channel1.capacity = 1000

agent.sinks.cassandraSink.channel = channel1

agent.sinks.cassandraSink.type = com.btoddb.flume.sinks.cassandra.CassandraSink
agent.sinks.cassandraSink.hosts = localhost
agent.sinks.cassandraSink.port = 9160
agent.sinks.cassandraSink.cluster-name = Logging
agent.sinks.cassandraSink.keyspace-name = logs
agent.sinks.cassandraSink.records-colfam = records

How should I add timestamp to header, is there another way for it?

**Comment by viktort** [comment]
Hi @salihkardan 

I don't think this is the same issue I had to resolve flume side. It looks like you need to define your own regex interceptor and get the timestamp out of the log data.

eg: This is an example of my log data from one of the services

``` js
 {"service":"example_service","event":"server_restart","timestamp":"1386090510581","uuid":"5kneh567-4bd8-49a1-8cd8-4cf142fb0bff","port":"8091","source_ip":"127.0.0.1","info":"example_service is alive on port 8989"}
```

then I extract the required data to add to event headers, ready for the flume-ng-cassandra-sink by:

``` sh
orion.sources.spoolDir.type = spooldir
orion.sources.spoolDir.spoolDir = /mnt/spoolingDirLocation
orion.sources.spoolDir.inputCharset = UTF-8
orion.sources.spoolDir.deserializer.maxLineLength = 209715200
orion.sources.spoolDir.deletePolicy = never
orion.sources.spoolDir.interceptors = addSrc addHost addTimestamp addUUID

orion.sources.spoolDir.interceptors.addSrc.type = regex_extractor
orion.sources.spoolDir.interceptors.addSrc.regex = \"service\"\:\"([^"]*)
orion.sources.spoolDir.interceptors.addSrc.serializers = s1
orion.sources.spoolDir.interceptors.addSrc.serializers.s1.name = src

orion.sources.spoolDir.interceptors.addUUID.type = regex_extractor
orion.sources.spoolDir.interceptors.addUUID.regex = \"uuid\"\:\"([^"]*)
orion.sources.spoolDir.interceptors.addUUID.serializers = s1
orion.sources.spoolDir.interceptors.addUUID.serializers.s1.name = key

orion.sources.spoolDir.interceptors.addHost.type = org.apache.flume.interceptor.HostInterceptor$Builder
orion.sources.spoolDir.interceptors.addHost.preserveExisting = false
orion.sources.spoolDir.interceptors.addHost.useIP = true
orion.sources.spoolDir.interceptors.addHost.hostHeader = host

orion.sources.spoolDir.interceptors.addTimestamp.type = regex_extractor
orion.sources.spoolDir.interceptors.addTimestamp.regex = \"timestamp\"\:\"([^"]*)
orion.sources.spoolDir.interceptors.addTimestamp.serializers = s1
orion.sources.spoolDir.interceptors.addTimestamp.serializers.s1.name = timestamp
```

Expanding on https://github.com/btoddb/flume-ng-cassandra-sink/issues/8 I reported, this was what I believe, a bug with the Spooling Directory Source in Flume 1.4

When my logs contained any special chars represented by 2 bytes in UTF-8 in my case the £ sign, check out the rest here http://www.utf8-chartable.de/ , when the data was being read in from spooling dir in chunks and one of those chunks happened to pull in the first byte of the special char, it was dropping the rest of the data in the file.

This is now fixed in Flume 1.5 which is still under development. I've cloned the dir and im compiling and packaging the code from that until 1.5 is released. This fixed the above issues and I havent seen any other bugs so happy to go to production with it.

Let me know if you require further info.

Viktor

**Comment by viktort** [comment]
I have started to see this error in production as well. Seems odd as timestamp event header is present but ends up as null at the point where its parsed to a long in FlumeLogEvent.java

``` java
public long getTimestamp() {
    return Long.parseLong(getHeader(HEADER_TIMESTAMP));
}
```

@salihkardan - did you manage to get to the bottom of this?

Getting this error in production very sporadically - investigating further now but any info would be great. cc @btoddb
